"""empty message

Revision ID: e9e80db9d9d6
Revises: fdd359e39198
Create Date: 2024-06-14 03:06:38.268838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9e80db9d9d6'
down_revision = 'fdd359e39198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UPeopleFavorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UPlanetFavorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planets_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planets_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('u_people_favorite')
    op.drop_table('u_planet_favorite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('u_planet_favorite',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], name='u_planet_favorite_planet_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='u_planet_favorite_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'planet_id', name='u_planet_favorite_pkey')
    )
    op.create_table('u_people_favorite',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('people_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], name='u_people_favorite_people_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='u_people_favorite_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'people_id', name='u_people_favorite_pkey')
    )
    op.drop_table('UPlanetFavorite')
    op.drop_table('UPeopleFavorite')
    # ### end Alembic commands ###
